//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleProgramForDBConn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExempluTabel
    {
        public int id { get; set; }
        public string ceva { get; set; }
        public string altceva { get; set; }
    }
}
